[package]
name = "responsive-image-to-hugo-template"
version = "0.1.2"
description = "A library and command line tool for managing images for use with a Hugo site"
license = "MIT"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2018"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
structopt = "0.3.22"
custom_error = "1.9.2"
zip = "0.5.13"
scraper = "0.12.0"
chrono = "0.4"
regex = "1"
tempfile = "3"
serde_json = "1.0.66"  
serde = "1.0.127"
serde_derive = "1.0"
rust-s3 = "0.18.11"
indicatif = "0.16.2"
base64 = "0.13.0"
num_cpus = "1.13"

[dev-dependencies]
assert_cmd = "1.0.8"
predicates = "1"
