[package]
name = "responsive-image-to-hugo-template"
version = "0.1.1"
description = "A library and command line tool for managing images for use with a Hugo site"
license = "MIT"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2018"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
structopt = "0.3.7"
custom_error = "1.7.1"
zip = "0.5.3"
scraper = "0.11.0"
chrono = "0.4"
regex = "1"
tempfile = "3"
serde_json = "1.0"  
serde = "1.0.104"
serde_derive = "1.0"
rust-s3 = "0.18.9"
indicatif = "0.13.0"
base64 = "0.11.0"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1"
