[package]
name = "responsive-image-to-hugo-template"
version = "0.1.2"
description = "A library and command line tool for managing images for use with a Hugo site"
license = "MIT"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2021"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
env_logger = "0.10.0"
log = "0.4.14"
structopt = "0.3.22"
custom_error = "1.9.2"
zip = "0.6.3"
scraper = "0.15.0"
chrono = "0.4"
regex = "1"
tempfile = "3"
serde_json = "1.0.72"  
serde = "1.0.130"
serde_derive = "1.0.130"
rust-s3 = {version = "0.32.3", features = ["default", "blocking", "tokio"]}
indicatif = "0.17.2"
base64 = "0.21.0"
num_cpus = "1.13"
aws-creds = "0.34.0"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
