[package]
name = "responsive-image-to-hugo-template"
version = "0.1.2"
description = "A library and command line tool for managing images for use with a Hugo site"
license = "MIT"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2021"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
env_logger = "0.10.0"
log = "0.4.20"
structopt = "0.3.26"
custom_error = "1.9.2"
zip = "0.6.6"
scraper = "0.17.1"
chrono = "0.4.28"
regex = "1.9.4"
tempfile = "3.8.0"
serde_json = "1.0.105"  
serde = "1.0.188"
serde_derive = "1.0.188"
rust-s3 = {version = "0.33.0", features = ["default", "blocking", "tokio"]}
indicatif = "0.17.6"
base64 = "0.21.3"
num_cpus = "1.16.0"
aws-creds = "0.35.0"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.5"
